#spring.application.name=ssundev-project
#spring:
#  datasource:
#    url: jdbc:oracle:thin:@//localhost:1521/orcl
#    username: ssundev
#    password: ssundev
#    driver-class-name: oracle.jdbc.OracleDriver

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: ssundev
    password: ssundev
    driver-class-name: oracle.jdbc.OracleDriver

#mybatis:
# mapper-locations: classpath*:mappers/*.xml